### ISSUE TITLE
[BUG] "musicify shuffle" works but "musicify play shuffle"?

### ISSUE THREAD

**Issue by MuratDev7** [RubenHetKonijn/musicify#16]
**Describe the bug**
Bug happens when you run command "musicify play shuffle" but doesn't happen while doing "musicify shuffle"

**To Reproduce**
1. Open computer/turret
2. Type 'musicify play shuffle'
3. See error

**Expected behavior**
It needed to play musics in shuffle mode

**Setup (please complete the following information):**
 - Type of Computer: Normal Turtle
 - Browser Chrome
 - Version 0.05

**Additional context**
Probably forgotten to remove the old shuffle command

**Comment by RubenHetKonijn** [comment]
Ima go fix this real quick

**Comment by RubenHetKonijn** [comment]
fixed.
