### ISSUE TITLE
[BUG] Autoupdate comes stuck in a loop

### ISSUE THREAD

**Issue by RubenHetKonijn** [RubenHetKonijn/musicify#17]
**Describe the bug**

**To Reproduce**
1. Run `musicify`

**Expected behavior**
It should just update

**Screenshots**

![2021-01-01-14-19-23](https://user-images.githubusercontent.com/64010592/103439470-7e437c00-4c3d-11eb-9720-4564ddd36bc4.gif)

**Comment by BlackDragon-B** [comment]
You're fault when updating program on github.
