### ISSUE TITLE
[SONG REQUEST] Deaft Punk

### ISSUE THREAD

**Issue by TNTTheLagger** [RubenHetKonijn/musicify#3]
## The song name and artist:
All in the order as they are in the playlist:

Daft Punk - Around The World
Daft Punk - One More Time
Daft Punk - Harder, Better, Faster, Stronger
Daft Punk - Something About Us
Daft Punk - Technologic (Radio Edit) 
Daft Punk - Digital Love

## Links to the song
https://www.youtube.com/watch?v=dwDns8x3Jb4
https://www.youtube.com/watch?v=n6RTF4OPzf8
https://www.youtube.com/watch?v=yydNF8tuVmU
https://www.youtube.com/watch?v=em0MknB6wFo
https://www.youtube.com/watch?v=TGY7ScyU_2c
https://www.youtube.com/watch?v=4whD6uAryMs

**Comment by RubenHetKonijn** [comment]
Working on it right now

**Comment by RubenHetKonijn** [comment]
Okay I changed the index, could you check if it works?

**Comment by RubenHetKonijn** [comment]
works
