### ISSUE TITLE
[SONG REQUEST] Just Shapes and Beats

### ISSUE THREAD

**Issue by BlackDragon-B** [RubenHetKonijn/musicify#6]
## The song name and artist:
Whole Just Shapes and Beats playlist.

## Links to the song
https://we.tl/t-68A0KgmSJh
If the link expires then contact me.

**Comment by RubenHetKonijn** [comment]
Who is the artist of the playlist?

**Comment by RubenHetKonijn** [comment]
Ah I understand the structure, it's number - artist - name
