### ISSUE TITLE
[BUG] installer installing wrong files

### ISSUE THREAD

**Issue by Commandcracker** [RubenHetKonijn/musicify#60]
**Describe the bug**
The installer is installing files from the latest tag and from the main branch.
This may result in errors.
currently it's installing an old /bin/musicify.lua this results in youcube being missing cause its now youcubeapi

**Expected behavior**
Download only from the latest releases or from the main branch

**Comment by EmmaKnijn** [comment]
I fixed this, I thought that this could happen but forgor :skull:
