### ISSUE TITLE
[FEATURE] Dynamically requesting index, you donkey.

### ISSUE THREAD

**Issue by BlackDragon-B** [RubenHetKonijn/musicify#7]
**Is your feature request related to a problem? Please describe.**
Add dynamically getting the index file.

**Describe the solution you'd like**
Dont do it manually. Instead use Nodejs with expressjs and display the table by reading the folder and generating an id.

**Comment by Tomodachi94** [comment]
I could probably make a web backend for this in Python.

**Comment by SecretForgesDeveloper** [comment]
i dont think he will do that. thats just waste of time

**Comment by RubenHetKonijn** [comment]
If you want to help with this project, you can always make a pull request
